INSERT INTO author(name) VALUES ('Михаил Булгаков');
INSERT INTO author(name) VALUES ('Антуан де Сент-Экзюпери');
INSERT INTO author(name) VALUES ('Александр Дюма');
INSERT INTO author(name) VALUES ('Аркадий и Борис Стругацкие');

INSERT INTO genre (name) VALUES ('Роман');
INSERT INTO genre (name) VALUES ('Проза');
INSERT INTO genre (name) VALUES ('Фантастика');
INSERT INTO genre (name) VALUES ('Приключения');

INSERT INTO book(author_id, genre_id, name) VALUES (1, 1, 'Мастер и Маргарита');
INSERT INTO book(author_id, genre_id, name) VALUES (1, 2, 'Белая гвардия');
INSERT INTO book(author_id, genre_id, name) VALUES (1, 3, 'Собачье сердце');
INSERT INTO book(author_id, genre_id, name) VALUES (2, 2, 'Маленький принц');
INSERT INTO book(author_id, genre_id, name) VALUES (3, 4, 'Граф Монте-Кристо');
INSERT INTO book(author_id, genre_id, name) VALUES (4, 3, 'Трудно быть Богом');
INSERT INTO book(author_id, genre_id, name) VALUES (4, 3, 'Пикник на обочине');
INSERT INTO book(author_id, genre_id, name) VALUES (4, 3, 'Улитка на склоне');
INSERT INTO book(author_id, genre_id, name) VALUES (4, 3, 'Обитаемый остров');
INSERT INTO book(author_id, genre_id, name) VALUES (4, 3, 'Отель у погибшего альпениста');

INSERT INTO review(book_id, review) VALUES (1,  'Review-01.1 - Мастер');
INSERT INTO review(book_id, review) VALUES (1,  'Review-01.2 - Мастер');
INSERT INTO review(book_id, review) VALUES (2,  'Review-02.1 - гвардия');
INSERT INTO review(book_id, review) VALUES (2,  'Review-02.2 - гвардия');
INSERT INTO review(book_id, review) VALUES (3,  'Review-03.1 - сердце');
INSERT INTO review(book_id, review) VALUES (3,  'Review-03.2 - сердце');
INSERT INTO review(book_id, review) VALUES (3,  'Review-03.3 - сердце');
INSERT INTO review(book_id, review) VALUES (4,  'Review-04.1 - M принц');
INSERT INTO review(book_id, review) VALUES (4,  'Review-04.2 - M принц');
INSERT INTO review(book_id, review) VALUES (5,  'Review-05.1 - Граф MK');
INSERT INTO review(book_id, review) VALUES (5,  'Review-05.2 - Граф MK');
INSERT INTO review(book_id, review) VALUES (5,  'Review-05.3 - Граф MK');
INSERT INTO review(book_id, review) VALUES (6,  'Review-06.1 - Трудно');
INSERT INTO review(book_id, review) VALUES (6,  'Review-06.2 - Трудно');
INSERT INTO review(book_id, review) VALUES (7,  'Review-07.1 - Пикник');
INSERT INTO review(book_id, review) VALUES (7,  'Review-07.2 - Пикник');
INSERT INTO review(book_id, review) VALUES (7,  'Review-07.3 - Пикник');
INSERT INTO review(book_id, review) VALUES (8,  'Review-08.1 - Улитка');
INSERT INTO review(book_id, review) VALUES (8,  'Review-08.2 - Улитка');
INSERT INTO review(book_id, review) VALUES (8,  'Review-08.3 - Улитка');
INSERT INTO review(book_id, review) VALUES (8,  'Review-08.4 - Улитка');
INSERT INTO review(book_id, review) VALUES (9,  'Review-09.1 - остров');
INSERT INTO review(book_id, review) VALUES (9,  'Review-09.1 - остров');
INSERT INTO review(book_id, review) VALUES (10, 'Review-10.1 - Отель');
INSERT INTO review(book_id, review) VALUES (10, 'Review-10.2 - Отель');
INSERT INTO review(book_id, review) VALUES (10, 'Review-10.3 - Отель');
INSERT INTO review(book_id, review) VALUES (10, 'Review-10.4 - Отель');
