spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myDB
    username: admin
    password: admin
  sql:
    init:
      mode: always
      #data-locations: data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: false

management:
  endpoints:
    web:
      exposure:
        include: "health, logfile, metrics"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    root: info
  file:
    name: logs/app.log
