spring:
  main:
    allow-circular-references: true

  batch:
    job:
      enabled: false

  mongodb:
    embedded:
      version: 3.4.0

  data:
    mongodb:
      host: localhost
      port: 27017
      database: bookDb

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.batch.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
